version: '2'
services:
  www:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./dev:/var/www
      - ./config:/etc/nginx
    ports:
      - 80:80
      - 443:443
networks:
  default:
    external:
      name: service
